customhost = "database-1.cw9o9ev3gnbo.us-east-1.rds.amazonaws.com"
customuser = "rahulrawat"
custompass = "Devops123"
customdb = "employee"
custombucket = "addemp-rrproject"
customregion = "us-east-1"
